services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bigdata
      POSTGRES_PASSWORD: bigdata
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql
      - ./data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./data:/hostdata

  memgraph:
    image: memgraph/memgraph-mage:latest
    ports:
      - "7687:7687"
      - "7444:7444"
    volumes:
      - ./data:/data

  memgraph-lab:
    image: memgraph/lab:latest
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph

volumes:
  pgdata:
  mongodata:
